### PR TITLE
Fix: empty packet structure error

### PR DESCRIPTION
**Pull request by georgolden**
https://github.com/metarhia/metacom/issues/231

https://github.com/metarhia/metacom/pull/232#pullrequestreview-745393563

- [x] tests and linter show no problems (`npm t`)
- [x] tests are added/updated for bug fixes and new features
- [x] code is properly formatted (`npm run fmt`)
- [ ] description of changes is added in CHANGELOG.md

### CODE REVIEW

**Comment by georgolden** [comment]
Sorry for creating another pull request, I closed previous with miss click :(

**Comment by rohiievych** [comment]
The problem is that a new version of ws package populates messages as bytes by default.
So instead of modifying string message handler, we can just divide messages into string and binary in server.js.
This is a part of [metacom streams implementation](https://github.com/metarhia/metacom/pull/233):
```js
connection.on('message', (data, isBinary) => {
  if (isBinary) channel.binary(data);
  else channel.message(data.toString());
});
```

**Comment by georgolden** [comment]
https://github.com/metarhia/metacom/pull/232#pullrequestreview-745393563
With this approach, we will have the same 2 times serialization at every message. First data.toString, second JSON.parse. All messages are strings packed in to Uint8Array (Buffer).

**Review by tshemsedinov — APPROVED** [review]
I am going to land this

**Comment by tshemsedinov** [comment]
Landed in https://github.com/metarhia/metacom/commit/a341730f514e1e538b56bd041efd81268950a41c

**Pull request closed without merging**
