### PR TITLE
Metacom streams

### PR DESCRIPTION
**Pull request by tshemsedinov**
Closes: https://github.com/metarhia/metacom/issues/76
PR-URL: https://github.com/metarhia/metacom/pull/233
Co-authored-by: Timur Shemsedinov <timur.shemsedinov@gmail.com>

### CODE REVIEW

**Comment by tshemsedinov** [comment]
@rohiievych are we ready to land?

**Comment by rohiievych** [comment]
> @rohiievych are we ready to land?

It's better to resolve all planned issues for streams before mering with master

**Comment by rohiievych** [comment]
@tshemsedinov 
Updated README.md with usage examples

**Comment by tshemsedinov** [comment]
Landed in https://github.com/metarhia/metacom/commit/110c4a3fa68e97a8b4bd0fec8c3d1a7ba01a26c7, https://github.com/metarhia/metacom/commit/5bd94a47c0b148c4908f60f464b2893bb138f109, and https://github.com/metarhia/metacom/commit/029c44a0fb455ab7f83adef2127c4433f4bbddcd

**Pull request closed without merging**
