### PR TITLE
Rework Channel and Server

### PR DESCRIPTION
**Pull request by tshemsedinov**
- [x] tests and linter show no problems (`npm t`)
- [x] code is properly formatted (`npm run fmt`)
- [x] description of changes is added in CHANGELOG.md

### CODE REVIEW

**Comment by OleksiiKachan** [comment]
@tshemsedinov I can update d.ts

**Comment by tshemsedinov** [comment]
Would be great @OleksiiKachan it looks like everything works in this implementation and signatures will not change dramatically )

**Comment by OleksiiKachan** [comment]
@tshemsedinov I have a branch with updated typings but I cannot push to metarhia/metacom. getting permission denied. I'd prefer not to fork it

**Comment by tshemsedinov** [comment]
@OleksiiKachan, Rebased on master, fixups applied, access granted, welcome

**Comment by OleksiiKachan** [comment]
@tshemsedinov https://github.com/metarhia/metacom/pull/236

**Comment by tshemsedinov** [comment]
Landed in https://github.com/metarhia/metacom/commit/1cebc0ca1e2b9bd6d76f70fedc686f288ccb4eac, https://github.com/metarhia/metacom/commit/b4fd0a0edcc277826e6f91895891bcf4b0d93603, and https://github.com/metarhia/metacom/commit/c008498636ff9929ff12d738ba904f1c484e7376

**Pull request closed without merging**
