### PR TITLE
Support CORS headers

### PR DESCRIPTION
**Pull request by MarhiievHE**
https://github.com/metarhia/impress/issues/1687#issue-1039469103

- [x] tests and linter show no problems (`npm t`)
- [x] code is properly formatted (`npm run fmt`)
- [x] description of changes is added in CHANGELOG.md

### CODE REVIEW

**Comment by tshemsedinov** [comment]
Moving all `HEADERS` to `lib/server.js` is not ok, it's better to hold them in `lib/http.js`, just patch from server, but exporting/importing `HEADERS` also not a good idea, I'd prefer to export function `addHeaders` from `lib/http.js`.

**Comment by MarhiievHE** [comment]
OK, do I need to delete the last commit before pushing the new implementation? Or do I need to just make a new fixup for this commit: https://github.com/metarhia/metacom/pull/271/commits/2125df027d335849bed9c9b24e8556340285c482?

**Comment by tshemsedinov** [comment]
@MarhiievHE it is not important, I'll squash all commits to single landing this PR

**Review by tshemsedinov — APPROVED** [review]

**Comment by tshemsedinov** [comment]
Landed in https://github.com/metarhia/metacom/commit/9b9615003a299c3f57f97f76aeffe2e498ed4ebe

**Pull request closed without merging**
